WIP: Automatic configurator for linstor-satellite
kvaps/kube-linstor pull request #35
Opened 2021-04-20 14:18 UTC by kvaps

This PR will implement additional confiscator container for linstor-satllite, it will do two main things:
- Add node to the cluster
- Define storage pools on the node

This code is going to reimplement the functionality added by https://github.com/kvaps/kube-linstor/pull/26 and https://github.com/kvaps/kube-linstor/pull/31

2021-04-21 23:01 UTC, kvaps commented
@jbanety @t3hmrman the PR is ready for review.
It would be really nice if someone could confirm that it is working in your environment as good as mine.

Thank you!

2021-04-22 06:14 UTC, jbanety commented
Hi @kvaps, 
I'll try this on a new cluster this morning.

2021-04-22 09:38 UTC, t3hmrman commented
Hi @kvaps it might take me a while to find time to test this (hopefully by end of next week), will update here if/when I get to it!

2021-04-22 13:34 UTC, jbanety requested changes
Nice job !
Some fixes here.

2021-04-22 13:34 UTC, jbanety commented on helm/kube-linstor/scripts/functions.sh
> +  "name": "",
$NODE_NAME is missing here.
```shell
  "name": "$NODE_NAME",
```

2021-04-22 13:34 UTC, jbanety commented on helm/kube-linstor/templates/satellite-daemonset.yaml
> +        command:
We need `privileged` context to display LVM volume groups.
```
        securityContext:
          privileged: true
```

2021-04-22 13:44 UTC, kvaps commented
@jbanety thanks for review!

2021-04-23 14:19 UTC, merged